name: Test

on:
  push:

env:
  GO_VERSION: 1.19

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install Dependencies
        run: |
          go install -v github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run tests
        run: |
          go test -v -json ./lib/... -cover | gotestfmt

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        year:
          - 2015
          - 2021
          - 2022
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install Dependencies
        run: |
          go install -v github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run tests
        run: |
          go test -v -json ./y${{ matrix.year }}/... -cover | gotestfmt
